services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_HOST: host.docker.internal
      FRONTEND_ASSETS: /frontend/assets
      FRONTEND_DIST: /frontend/dist
  frontend:
    build: ./frontend
    ports:
      - "3334:3334"
    environment:
      DB_HOST: host.docker.internal